version: '3.8'

services:
  # Aplicação Laravel
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ranhentos_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ranhentos_network
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ranhentos_db
      - DB_USERNAME=ranhentos_user
      - DB_PASSWORD=ranhentos_password

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: ranhentos_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx:/etc/nginx/conf.d
    networks:
      - ranhentos_network
    depends_on:
      - app

  # PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: ranhentos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ranhentos_db
      POSTGRES_USER: ranhentos_user
      POSTGRES_PASSWORD: ranhentos_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ranhentos_network

  # Redis (para cache e sessions)
  redis:
    image: redis:7-alpine
    container_name: ranhentos_redis
    restart: unless-stopped
    networks:
      - ranhentos_network

volumes:
  postgres_data:

networks:
  ranhentos_network:
    driver: bridge
